version: '3'
services:
  frontend:
    container_name: frontendd
    image: frontend 
    build: ./frontend 
    ports:
      - 3000:3000
    depends_on:
      - backend



  backend:
    container_name: backend
    image: backend
    build: ./backend
    volumes:
      - ./backend/:/app/
    expose:
      - 5003
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
       - db


  
  db:
    container_name: postre_ex
    image: postgres:12
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    command: -p 5434
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
    pgdata: 
    #db1-data: